##Query Spark Tables

One of the advantages of the DataFrame interface is that it is possible to run SQL queries on the tables in the Spark cluster. 

One of the tables in the cluster is the flights table, and the table contains a row for every flight that left Portland International Airport (PDX) or Seattle-Tacoma International Airport (SEA) in 2014 and 2015.

Running a query on this table is as easy as using the .sql() method on the SparkSession. This method takes a string containing the query and returns a DataFrame with the results!

In [0]:
# Don't change this query
query = "FROM flights SELECT * LIMIT 10"

# Get the first 10 rows of flights
flights10 = spark.sql(query)

# Show the results
flights10.show()